services:
  - type: web
    name: vedaa-flask-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: MONGO_URI
        scope: build,runtime
        value: mongodb+srv://ismail:ismail123@cluster0.t63ghmf.mongodb.net/?appName=Cluster0
      - key: MONGO_DB
        value: crmdb
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: password
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "0"
